package com.example.minesweeper;

public enum SharedPreferences_Keys {
    USER_INFORMATION_SP,
    USERNAME,
    EMAIL_ADDRESS,
    PASSWORD,
    SETTINGS_INFORMATION_SP,
    DIFFICULTY,
    BACKGROUND_MUSIC_STATE,
    CHOSEN_SOUNDTRACK,
    STATS_INFORMATION_SP,
    HIGH_SCORE;
}