package com.example.minesweeper.JavaClasses;

public enum SharedPreferences_Keys {
    USER_INFORMATION_SP,
    USERNAME,
    EMAIL_ADDRESS,
    PASSWORD,
    SETTINGS_INFORMATION_SP,
    DIFFICULTY,
    BACKGROUND_MUSIC_STATE,
    CHOSEN_SOUNDTRACK,
    STATS_INFORMATION_SP,
    GAMES_PLAYED,
    WINS,
    LOSES,
    SCORE,
    TIME,
    AVERAGE_TIME,
    WIN_PERCENTAGE,
    LOSE_PERCENTAGE,
    GAMES_RESULTS,
    LONGEST_WINNING_STREAK,
    LONGEST_LOSING_STREAK,
    CURRENT_STREAK;
}